# This is a hands-on task to create the cloudformation stack with
# 2 EC2 instances in total & one s3 bucket
# Webserver with 8gb EBS
# Appserver with 10gb EBS
# One S3 bucket to store invoice pds files

Resources:
  webserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0022f774911c1d690"
      InstanceType: "t2.micro"
      KeyName: "eva"
      BlockDeviceMappings:
      - DeviceName: "/dev/sdm"
        Ebs:
          VolumeType: "io1"
          Iops: 100
          DeleteOnTermination: true
          VolumeSize: 8
  appserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0022f774911c1d690"
      InstanceType: "t2.micro"
      KeyName: "eva"
      BlockDeviceMappings:
      - DeviceName: "/dev/sdm"
        Ebs:
          VolumeType: "io1"
          Iops: 100
          DeleteOnTermination: true
          VolumeSize: 10
  kelvins3bucket:
     Type: AWS::S3::Bucket
     Properties:
       AccessControl: "PublicRead"
